

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace exam
{

    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class DBSettings : DbContext
    {
        static DBSettings _context;

        static public DBSettings getInstance()
        {
            if (_context == null)
            {
                _context = new DBSettings();
            }
            return _context;
        }
        private DBSettings()
            : base("name=DBSettings")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<ExitCauses> ExitCauses { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TrafficViewer> TrafficViewer { get; set; }
        public virtual DbSet<Users> Users { get; set; }

    }
}

